### PR TITLE
Add 'open(java.sql.DataSource) method to POSTGIS and H2GIS.

### PR DESCRIPTION
**Pull request by SPalominos**
Add to `H2GIS` and `POSTGIS` an `open(java.sql.DataSource)` method.
Linked to #171

### CODE REVIEW

**Comment by ebocher** [comment]
I don't understand this PR and why there is a new object DataBaseTable

**Comment by ebocher** [comment]
Is there some tests to valid this change ?

**Comment by SPalominos** [comment]
@ebocher I'va add a unit test on H2GIS in the last PR

**Comment by ebocher** [comment]
Thanks

**Pull request merged**
