### PR TITLE
Changes how mapping is written.

### PR DESCRIPTION
**Pull request by SPalominos**
Changes how the mapping is written :
``` groovy
def mapper = new ProcessMapper()
mapper.out(out: process).in(in: process)
mapper.out(out: process).in(in: process)
mapper.out(out: process).in(in: process)
```

The order is out -> in to keep the lecture direction of a diagram (you link process n to proces n+1).

There is some limitation. the part `out/in: process` cannot be written `process: out/in` because groovy interpret it as `Map<String, Object> so the process have to be the second argument.
Character like `<`,`<-`,`>`,`<=>` ... are reserved and can't be used.

@ebocher , @j3r3m1 What do you think about this new syntax ?

### CODE REVIEW

**Comment by j3r3m1** [comment]
I do not feel really confident with the multiple use of in and out (for processes and mappers).

Would it be possible to do something like:
``` java
def mapper = new ProcessMapper()
mapper.arrow(out: process to in: process)
mapper.arrow(out: process to in: process)
mapper.arrow(out: process to in: process)
```

**Comment by SPalominos** [comment]
Groovy won't be able to interpret `out: process to in: process`.
It could be `mapper.arrow(out: process, in: process)`.

What do you think of `.link(` instead of `.arrow(` ?

**Comment by ebocher** [comment]
mapper.link(out: process, in: process)
is good for me

**Comment by j3r3m1** [comment]
Brilliant, OK for me as well

**Comment by SPalominos** [comment]
Ok, I'll do the changes in this PR.

**Pull request merged**
